[package]
name = "dendrite_macros"
version = "0.1.0"
authors = ["Jeroen van Maanen"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
anyhow = "^1.0"
log = "^0.4"
quote = "^1.0"
syn = "^1.0"
